<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,ref,shallowRef} from 'vue'
import {GameLinkClient} from '../../../../sdk/js/gamelink.js'
import type {GameLinkMember,GameLinkMessage} from '../../../../sdk/js/gamelink.js'
import RoomInviteButton from '../shared/RoomInviteButton.vue'
import UiIcon from '../shared/UiIcon.vue'
import CardFace from './CardFace.vue'
import {useBattleInteraction} from './useBattleInteraction'
import {apply,botAction,cardArt,cards,createPlayers,findCard,fresh,view,heroes,heroIds} from './engine'
import type {Action,State,View,HeroId} from './engine'
const client=shallowRef<GameLinkClient>(),members=ref<GameLinkMember[]>([]),self=ref(''),code=ref(''),host=ref(''),preview=ref(false),ready=ref(false),error=ref(''),peers=ref<string[]>([]),screen=ref<View>(view(fresh(),'')),selected=ref<number>(),attacker=ref(''),power=ref(false),rules=ref(false),book=ref(false),bookHero=ref('all'),clock=ref(Date.now())
let master:State=fresh(),timer=0,botAt=0,lastSync=0,disposed=false,pending=false
const library=computed(()=>cards.filter(c=>bookHero.value==='all'||(bookHero.value==='neutral'?!c.hero:c.hero===bookHero.value)))
const isHost=computed(()=>preview.value||host.value===self.value),me=computed(()=>screen.value.players.find(p=>p.id===self.value)),active=computed(()=>screen.value.players[screen.value.turn]),myTurn=computed(()=>screen.value.phase==='battle'&&active.value?.id===self.value),others=computed(()=>screen.value.players.filter(p=>p.id!==self.value)),online=computed(()=>preview.value||(!!host.value&&(host.value===self.value||peers.value.includes(host.value)))&&screen.value.players.filter(p=>p.hp>0).every(p=>members.value.some(m=>m.id===p.id)&&(p.id===self.value||peers.value.includes(p.id)))),choice=computed(()=>selected.value===undefined?undefined:findCard(me.value?.hand[selected.value]||'')),targeting=computed(()=>attacker.value||power.value||choice.value&&['damage','heal','buff','freeze'].includes(choice.value.kind)),timeLeft=computed(()=>Math.min(60,Math.max(0,Math.ceil((screen.value.deadline-clock.value)/1000)))),winner=computed(()=>screen.value.players.find(p=>p.id===screen.value.winner)?.name||'无人'),turnText=computed(()=>screen.value.phase==='waiting'?(members.value.length>=2?'两人即可开始':'等待一位朋友'):screen.value.phase==='done'?`${winner.value} 获胜`:!online.value?'等待玩家重新连接':myTurn.value?'你的回合':`${active.value?.name} 的回合`)
const {desktop,drag,dragCard,hover,hoverCard,effects,flights,announcement,dropZone,aimed,arrow,blocked,highlight,startCard,startUnit,startPower}=useBattleInteraction(screen,self,myTurn,online,{reset:resetChoice,pick,selectUnit,power:usePower,play,target,canTarget})
const heroPortrait=(hero:HeroId)=>cardArt({warrior:'ironlord',mage:'arcanist',hunter:'stalker',priest:'acolyte'}[hero])
const handStyle=(i:number)=>({'--fan-angle':`${(i-((me.value?.hand.length||1)-1)/2)*3.2}deg`,'--fan-lift':`${Math.abs(i-((me.value?.hand.length||1)-1)/2)**2*2.5}px`,'--card-order':i,'--hand-count':me.value?.hand.length||1})
function send(kind:string,data:unknown,target?:string){client.value?.send('hearth-'+kind,data,{reliability:'reliable',...(target?{target}:{})})}
function resetChoice(){selected.value=undefined;attacker.value='';power.value=false}
function persist(){if(code.value&&isHost.value)sessionStorage.setItem('hearth-v4:'+code.value+':'+self.value,JSON.stringify(master))}
function sync(target?:string){if(!isHost.value)return;screen.value=view(master,self.value);persist();for(const m of members.value)if(m.id!==self.value&&(!target||target===m.id))send('view',view(master,m.id),m.id)}
function lobby(){if(screen.value.phase!=='waiting')return;host.value=[...members.value].sort((a,b)=>a.id.localeCompare(b.id))[0]?.id||'';if(isHost.value){master.players=createPlayers(members.value.map(m=>({...m,hero:screen.value.players.find(p=>p.id===m.id)?.hero})));master.rev=Math.max(master.rev,screen.value.rev)+1;sync()}}
function perform(from:string,a:Action){if(!isHost.value||!online.value)return;const reason=apply(master,from,a);if(reason){if(from===self.value)error.value=reason;else send('error',reason,from);return}error.value='';sync()}
function action(a:Omit<Action,'rev'>){if(pending||!online.value)return;resetChoice();const payload={...a,rev:screen.value.rev};if(isHost.value)perform(self.value,payload);else{pending=true;send('action',payload);window.setTimeout(()=>{pending=false},2500)}}
function pick(index:number){if(blocked()||!myTurn.value||!online.value)return;resetChoice();selected.value=index;error.value=''}
function play(position?:number){if(!choice.value||selected.value===undefined)return;if(['damage','heal','buff','freeze'].includes(choice.value.kind))return;action({type:'play',card:selected.value,...(typeof position==='number'?{position}:{})})}
function canTarget(id:string,uid?:string){if(!myTurn.value||!online.value)return false;const p=screen.value.players.find(p=>p.id===id),u=p?.units.find(u=>u.uid===uid);if(!p||p.hp<=0||uid&&!u)return false
 if(attacker.value)return id!==self.value&&(!p.units.some(u=>findCard(u.card).trait==='taunt')||!!u&&findCard(u.card).trait==='taunt')
 if(power.value)return me.value?.hero==='priest'||id!==self.value&&(me.value?.hero==='mage'||me.value?.hero==='hunter'&&!uid)
 if(choice.value?.kind==='heal')return true
 if(choice.value?.kind==='buff')return id===self.value&&!!u
 return !!choice.value&&id!==self.value&&(choice.value.kind==='damage'||choice.value.kind==='freeze'&&!!u)
}
function target(id:string,unit?:string){if(!canTarget(id,unit))return;if(attacker.value)action({type:'attack',unit:attacker.value,target:id,targetUnit:unit});else if(power.value)action({type:'power',target:id,targetUnit:unit});else action({type:'play',card:selected.value,target:id,targetUnit:unit})}
function selectUnit(uid:string){if(blocked()||!myTurn.value)return;if(choice.value&&['heal','buff'].includes(choice.value.kind)||power.value&&me.value?.hero==='priest'){target(self.value,uid);return}resetChoice();attacker.value=uid}
function usePower(){if(blocked()||!me.value)return;resetChoice();if(heroes[me.value.hero].target)power.value=true;else action({type:'power'})}
function selectHero(hero:HeroId){action({type:'class',hero})}
function restart(){if(!isHost.value)return;master=fresh();master.players=createPlayers(members.value.map(m=>({...m,hero:screen.value.players.find(p=>p.id===m.id)?.hero})));master.rev=screen.value.rev+1;resetChoice();sync()}
function receive(m:GameLinkMessage){if(!members.value.some(p=>p.id===m.from))return;try{
 if(m.kind==='hearth-request'){sync(m.from);return}
 if(m.kind==='hearth-action'&&isHost.value){const a=m.payload as Action;if(a&&Number.isSafeInteger(a.rev)&&['start','end','play','attack','power','class'].includes(a.type))perform(m.from,a);return}
 if(m.from!==host.value)return
 if(m.kind==='hearth-error'){error.value=String(m.payload);pending=false}
 if(m.kind==='hearth-view'){const v=m.payload as View;if(!v||!Number.isSafeInteger(v.rev)||v.rev<screen.value.rev||!Array.isArray(v.players)||v.players.length>4||!['waiting','battle','done'].includes(v.phase))return;const changed=v.rev!==screen.value.rev;screen.value=v;pending=false;if(changed)resetChoice();if(code.value)sessionStorage.setItem('hearth-view-v4:'+code.value+':'+self.value,JSON.stringify({host:host.value,state:v}))}
 }catch{error.value='同步数据异常，请等待重连'}}
async function leave(){try{await client.value?.leave()}finally{location.assign('/')}}
onMounted(async()=>{try{
 if(!new URLSearchParams(location.search).has('room')){preview.value=true;self.value='you';members.value=[{id:'you',name:'你'},{id:'bot-1',name:'赤焰'},{id:'bot-2',name:'霜羽'},{id:'bot-3',name:'岩牙'}].map(m=>({...m,virtual_ip:'',endpoint:''}));host.value='you';master.players=createPlayers(members.value);apply(master,'you',{type:'start',rev:0});sync();ready.value=true}
 else{const c=GameLinkClient.fromLocation();if(c.gameId!=='gamelink-wild-hearth')throw Error('房间类型不匹配');client.value=c;c.on('message',receive);c.on('members',list=>{members.value=list;if(ready.value)lobby()});c.on('peer-ready',p=>{peers.value=[...new Set([...peers.value,p.peerId])];send('request',{},p.peerId);sync(p.peerId)});c.on('peer-state',p=>{if(p.state!=='connected')peers.value=peers.value.filter(id=>id!==p.peerId)});c.on('error',e=>error.value=e.message);c.on('room-closed',()=>{ready.value=false;error.value='房间已关闭'});const joined=await c.joinFromLocation();if(disposed){c.dispose();return}self.value=joined.self_member.id;members.value=joined.room.members;code.value=joined.room.code;host.value=[...members.value].sort((a,b)=>a.id.localeCompare(b.id))[0]!.id;ready.value=true;const cached=sessionStorage.getItem('hearth-view-v4:'+code.value+':'+self.value);if(cached){try{const data=JSON.parse(cached);screen.value=data.state;host.value=data.host}catch{}}const saved=sessionStorage.getItem('hearth-v4:'+code.value+':'+self.value);if(saved&&isHost.value){try{master=JSON.parse(saved);screen.value=view(master,self.value)}catch{master=fresh()}}lobby();send('request',{});sync();for(const [id,status]of c.peerStates)if(status==='connected')peers.value.push(id)}
 timer=window.setInterval(()=>{clock.value=Date.now();if(!isHost.value)return;if(clock.value-lastSync>3000){sync();lastSync=clock.value}if(master.phase==='battle'){if(!online.value){master.deadline=Date.now()+60000;screen.value.deadline=master.deadline;return}if(preview.value&&master.players[master.turn]!.id!==self.value&&clock.value>botAt){perform(master.players[master.turn]!.id,botAction(master));botAt=clock.value+1100}else if(clock.value>=master.deadline)perform(master.players[master.turn]!.id,{type:'end',rev:master.rev})}},500)
 }catch(e){error.value=e instanceof Error?e.message:String(e)}})
onBeforeUnmount(()=>{disposed=true;clearInterval(timer);client.value?.dispose()})
</script>
<template>
<main class="hearth" :class="{'desktop-battle':desktop&&screen.phase!=='waiting','is-dragging':drag?.active}"><header class="hearth-header"><a href="/" class="hearth-brand"><UiIcon name="neon"/><span>狂野炉石<small>WILD HEARTH</small></span></a><span class="room-tag">{{code||'单人练习'}} · {{members.length}}/4</span><RoomInviteButton v-if="code" game-id="gamelink-wild-hearth" :room-code="code" :member-count="members.length" :max-members="4"/><button v-if="preview" class="gl-action" @click="restart">职业</button><button class="gl-action" @click="book=!book"><UiIcon name="copy"/>图鉴</button><button class="gl-action" @click="rules=!rules"><UiIcon name="help"/>规则</button><button class="gl-action" aria-label="退出游戏" @click="leave"><UiIcon name="exit"/></button></header>
<section v-if="rules" class="hearth-rules"><b>2–4 人混战 · 最后存活者获胜</b><p>每人 30 点生命，起手四张牌。从统一随机牌堆发牌，轮到你时抽一张牌、增加一个法力水晶（最多 10）并恢复法力；手牌最多 10 张，随从最多 5 个。随从入场需等下一回合攻击，冲锋除外。攻击随从会互相造成伤害；攻击有嘲讽随从的玩家时，必须先攻击其嘲讽随从。法术不受嘲讽限制。</p><p>四个职业的技能均消耗 2 法力，每回合一次：战士加 3 护甲；法师造成 1 点伤害；猎手对敌方英雄造成 2 点伤害；牧师治疗 3 点生命。圣盾抵挡一次伤害；冻结跳过下回合攻击；战吼在入场触发，亡语在随从死亡时触发。每回合 60 秒，超时自动结束；公共牌堆用尽后抽牌受到递增疲劳伤害。桌面拖动手牌到战场出牌，拖动随从到敌方目标攻击；有目标的法术和英雄技能拖向目标释放。松开到无效位置即可取消，Esc 也可取消。手机点选手牌或己方随从，再点击目标。</p><button v-if="preview" class="gl-action" @click="restart();rules=false">重新选择练习职业</button><button class="gl-action" @click="rules=false">收起规则</button></section>
<section v-if="book" class="card-book"><header><b>卡牌图鉴 · 54 种</b><select v-model="bookHero" aria-label="筛选卡牌职业"><option value="all">所有卡牌</option><option value="neutral">中立卡牌</option><option v-for="id in heroIds" :key="id" :value="id">{{heroes[id].name}}</option></select><button class="gl-action" aria-label="关闭卡牌图鉴" @click="book=false"><UiIcon name="close"/></button></header><div class="book-grid"><CardFace v-for="c in library" :key="c.id" :card="c"/></div></section>
<p v-if="error" class="hearth-error" role="alert">{{error}}</p>
<section v-if="ready" class="hearth-table">
<div class="battle-heading"><span class="live-mark"></span><b>{{turnText}}</b><span v-if="screen.phase==='battle'">第 {{screen.round}} 轮 · {{timeLeft}} 秒</span></div>
<div v-if="screen.phase==='waiting'" class="hearth-lobby"><UiIcon name="neon"/><h1>一片荒野，等你来战</h1><p>两人即可开始，最多四人自由混战。没有阵营，最后存活者获胜。</p><div class="lobby-players"><span v-for="m in members" :key="m.id">{{m.name}}<small>{{screen.players.find(p=>p.id===m.id)?.hero?heroes[screen.players.find(p=>p.id===m.id)!.hero].name:'选择职业中'}}</small></span><span v-for="i in Math.max(0,4-members.length)" :key="i" class="empty-seat">等待加入</span></div><div class="hero-picker"><button v-for="id in heroIds" :key="id" :class="{chosen:me?.hero===id}" @click="selectHero(id)"><UiIcon :name="id==='warrior'?'target':id==='hunter'?'plane':id==='priest'?'plus':'neon'"/><b>{{heroes[id].name}}</b><span>{{heroes[id].power}} · 2 法力</span><small>{{heroes[id].text}}</small></button></div><p class="deck-note">54 种卡牌各两张组成公共随机牌堆。轮到谁就给谁发一张，任何职业都能使用抽到的卡。职业只决定英雄技能，可以重复选择。</p><button class="hearth-primary" :disabled="members.length<2||members.length>4||!online" @click="action({type:'start'})">{{members.length<2?'等待一位朋友':!online?'等待连接完成':`${members.length} 人开始混战`}}</button></div>
<template v-else>
<div class="battle-stage"><div class="table-grain" aria-hidden="true"></div><div class="opponents" :style="{'--opponent-count':others.length}"><article v-for="p in others" :key="p.id" class="hero-panel" :class="{eliminated:p.hp<=0,current:active?.id===p.id}"><div v-if="desktop" class="opponent-hand" aria-hidden="true"><i v-for="n in Math.min(10,p.handCount)" :key="n" :style="{'--back-angle':`${(n-(Math.min(10,p.handCount)+1)/2)*7}deg`}"></i></div><button class="hero-target" :data-target-player="p.id" :class="{targetable:canTarget(p.id),'drop-target':highlight(p.id)}" :disabled="!canTarget(p.id)" @click="target(p.id)"><span class="hero-avatar"><img :src="heroPortrait(p.hero)" alt="" draggable="false"/></span><span><b>{{p.name}}</b><small>{{p.hp<=0?'已出局':`${heroes[p.hero].name} · ${p.mana}/${p.maxMana} 法力 · ${p.handCount} 手牌`}}</small></span><strong class="hero-hp">{{Math.max(0,p.hp)}}<small>{{p.armor?`护甲 ${p.armor}`:'生命'}}</small></strong></button><div v-if="desktop||p.units.length" class="unit-row"><button v-for="u in p.units" :key="u.uid" class="unit" :data-target-player="p.id" :data-target-unit="u.uid" @mouseenter="hover=u.card" @mouseleave="hover=undefined" :class="{'drop-target':highlight(p.id,u.uid),shield:u.shield,frozen:u.frozen,taunt:findCard(u.card).trait==='taunt',targetable:canTarget(p.id,u.uid)}" :disabled="!canTarget(p.id,u.uid)" @click="target(p.id,u.uid)"><img class="unit-portrait" :src="cardArt(u.card)" alt="" draggable="false" loading="lazy" decoding="async"/><b>{{findCard(u.card).name}}</b><span><i>{{u.attack}}<span class="stat-label"> 攻</span></i><em>{{u.health}}<span class="stat-label"> 血</span></em></span><small>{{u.frozen?'冻结':u.shield?'圣盾':findCard(u.card).trait==='taunt'?'嘲讽':findCard(u.card).trait==='charge'?'冲锋':'随从'}}</small></button><span v-if="!p.units.length" class="empty-field">{{p.hp<=0?'英雄已倒下':'暂无随从'}}</span></div></article></div>
<div class="arena-divider"><span>荒野战场</span><small>{{desktop?(drag?.active?(aimed?'拖向发光目标，松开释放':'拖入战场，松开出牌'):'拖动卡牌出牌 · 拖动随从攻击'):(targeting?'点击目标完成行动':'最后存活的英雄获胜')}}</small></div>
<section v-if="me" class="your-field"><div class="unit-row your-units" data-summon-zone :style="{'--insert-position':drag?.position??me.units.length,'--unit-count':me.units.length}" :class="{'summon-zone-active':drag?.active&&dragCard?.kind==='unit','drop-ready':dropZone}"><span v-if="desktop&&dropZone&&dragCard?.kind==='unit'" class="summon-marker" aria-hidden="true"></span><span v-if="desktop&&drag?.active&&dragCard?.kind==='unit'" class="summon-hint">松开召唤 · {{me.units.length}} / 5</span><button v-for="u in me.units" :key="u.uid" class="unit" :data-target-player="me.id" :data-target-unit="u.uid" @pointerdown="startUnit($event,u.uid)" @mouseenter="hover=u.card" @mouseleave="hover=undefined" :class="{'drop-target':highlight(me.id,u.uid),targetable:canTarget(me.id,u.uid),shield:u.shield,frozen:u.frozen,available:myTurn&&u.ready&&!u.frozen,chosen:attacker===u.uid,taunt:findCard(u.card).trait==='taunt'}" :disabled="!myTurn||!online||(!u.ready||u.frozen)&&!canTarget(me.id,u.uid)" @click="selectUnit(u.uid)"><img class="unit-portrait" :src="cardArt(u.card)" alt="" draggable="false" loading="lazy" decoding="async"/><b>{{findCard(u.card).name}}</b><span><i>{{u.attack}}<span class="stat-label"> 攻</span></i><em>{{u.health}}<span class="stat-label"> 血</span></em></span><small>{{u.frozen?'冻结':u.shield?'圣盾':u.ready?'可攻击':'休整中'}}</small></button><span v-if="!me.units.length" class="empty-field">打出随从，建立你的战线</span></div>
<div class="your-hero"><button class="hero-target" :data-target-player="me.id" :disabled="!canTarget(me.id)" :class="{targetable:canTarget(me.id),'drop-target':highlight(me.id)}" @click="target(me.id)"><span class="hero-avatar"><img :src="heroPortrait(me.hero)" alt="" draggable="false"/></span><span><b>{{me.name}} · 你</b><small>{{heroes[me.hero].name}} · {{screen.pileCount}} 张公共牌堆</small></span><strong class="hero-hp">{{Math.max(0,me.hp)}}<small>{{me.armor?`护甲 ${me.armor}`:'生命'}}</small></strong></button><div class="mana"><div class="mana-gems" aria-hidden="true"><i v-for="n in me.maxMana" :key="n" :class="{spent:n>me.mana}"></i></div><b>{{me.mana}}<small>/ {{me.maxMana}}</small></b><span>法力水晶</span></div><button class="hero-power" @pointerdown="startPower" :class="{chosen:power}" :disabled="!myTurn||me.power||me.mana<2||!online" @click="usePower" :title="heroes[me.hero].text"><UiIcon :name="me.hero==='priest'?'plus':me.hero==='warrior'?'target':'neon'"/>{{heroes[me.hero].power}} <small>{{desktop?'2':'2 法力'}}</small></button><button class="hearth-primary end-turn" :disabled="!myTurn||!online" @click="action({type:'end'})">结束回合</button></div>
<div class="hero-extra"><span>{{heroes[me.hero].power}}：{{heroes[me.hero].text}}</span></div><div class="hand-heading"><b>你的手牌 <small>{{me.handCount}} / 10</small></b><span>{{me.hp<=0?'已出局，可以继续观战':desktop?'拖动出牌 · 悬停查看':'点选卡牌查看效果'}}</span></div><div class="hand"><button v-for="(id,i) in me.hand" :key="`${i}-${id}`" class="card-button" :style="handStyle(i)" @pointerdown="startCard($event,i)" @mouseenter="hover=id" @mouseleave="hover=undefined" :class="{chosen:selected===i,affordable:myTurn&&online&&me.mana>=findCard(id).cost&&(findCard(id).kind!=='unit'||me.units.length<5),'card-in-drag':drag?.active&&drag.kind==='card'&&drag.index===i}" :disabled="!myTurn||!online" @click="pick(i)"><CardFace :card="findCard(id)"/></button></div>
<div v-if="choice||attacker||power" class="selection-bar"><span>{{choice?`${choice.name} · ${choice.text}`:power?`${heroes[me.hero].power}：${heroes[me.hero].text}，点击目标`:'点击敌方英雄或随从进行攻击'}}</span><button v-if="choice&&!targeting" class="hearth-primary" :disabled="me.mana<choice.cost" @click="play()">打出卡牌</button><button class="gl-action" @click="resetChoice"><UiIcon name="close"/>取消</button></div></section>
</div><div v-if="screen.phase==='done'" class="victory"><h2>{{winner}}获胜</h2><button v-if="isHost" class="hearth-primary" @click="restart">再来一局</button><p v-else>等待房主开启下一局</p></div><details class="battle-log"><summary>战斗记录</summary><p v-for="(line,i) in screen.log" :key="i">{{line}}</p></details>
</template></section><p v-else class="hearth-loading">{{error||'正在进入荒野…'}}</p>
<Teleport to="body">
<div v-if="desktop&&drag?.active" class="battle-drag-layer" aria-hidden="true">
<svg v-if="aimed" class="aim-overlay"><defs><marker id="hearth-arrowhead" markerWidth="10" markerHeight="10" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" :fill="drag.valid?'#a9eda3':'#e9b267'"/></marker></defs><path class="aim-shadow" :d="arrow"/><path class="aim-line" :class="{valid:drag.valid}" :d="arrow" marker-end="url(#hearth-arrowhead)"/><circle :cx="drag.at.x" :cy="drag.at.y" r="22" :class="{valid:drag.valid}"/></svg>
<div v-if="dragCard" class="drag-card" :class="{aiming:aimed,valid:drag.valid}" :style="{left:`${drag.at.x}px`,top:`${drag.at.y}px`}"><CardFace :card="dragCard"/></div>
<span class="drag-instruction" :style="{left:`${drag.at.x}px`,top:`${drag.at.y+42}px`}">{{drag.valid?'松开释放':'移到发光目标 · Esc 取消'}}</span>
</div>
<div class="battle-effects" aria-hidden="true"><span v-for="e in effects" :key="e.id" class="battle-effect" :class="e.kind" :style="{left:`${e.x}px`,top:`${e.y}px`}"><img v-if="e.card" :src="cardArt(e.card)" alt=""/>{{e.text}}</span><img v-for="f in flights" :key="f.id" class="attack-flight" :src="cardArt(f.card)" alt="" :style="{left:`${f.from.x}px`,top:`${f.from.y}px`,'--flight-x':`${f.to.x-f.from.x}px`,'--flight-y':`${f.to.y-f.from.y}px`}"/></div>
<div v-if="desktop&&hoverCard&&!drag?.active&&!book" class="card-inspect" aria-hidden="true"><CardFace :card="hoverCard"/></div>
<div v-if="announcement&&screen.phase==='battle'" class="turn-announcement" role="status">{{announcement}}</div>
</Teleport>
</main>
</template>
